### ISSUE TITLE
Suggestion: Add the whole file path

### ISSUE THREAD

**Issue by facuacostag** [pentarex/react-native-gallery-manager#8]
Right now, the asset object return an uri like `assets-library://asset/asset.mp4?id=7ED0862F-75A0-4EDE-8096-0F5F695045C2&ext=mp4` is it possible to also retrieve the path like 
`file:///Users/pentarex/Library/Developer/CoreSimulator/Devices/81873DB4-A220-4F60-88B8-87521BB231E6/data/Containers/Data/Application/91EE6566-4D04-4E33-9608-EDB06DA6C6D2/Documents/8DAEDFBC-9E16-442D-A98F-E145F429DA0B.m4v` to use it with other libraries?

**Comment by pentarex** [comment]
Apple API is not returning the absolute url because of sandboxing. In order to retrieve this path I have to do additional request which probably will slow down this library. 
The converted video path is like this because I am already editing the video and I have the path already.

I am not sure what are you trying to do, maybe you can use the id or the filename of the asset.

**Comment by numandev1** [comment]
i also want to get file path not assets-library:// path

**Comment by numandev1** [comment]
@FacuAcosta did you got any solution?
